### ISSUE TITLE
Not compatible with latest (1.19.0) stripe version

### ISSUE THREAD

**Issue by JakubRacek** [rebelidealist/stripe-ruby-mock#184]
Hello, just getting an error:

```txt
  1) StripeTransactionWorker charge error Declined should transition to declined state
     Failure/Error: subject { StripeTransactionWorker.perform_async(1234, uuid) }
     ArgumentError:
       wrong number of arguments (6 for 3..5)
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/stripe-ruby-mock-2.0.0/lib/stripe_mock/instance.rb:61:in `mock_request'
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/stripe-ruby-mock-2.0.0/lib/stripe_mock/api/instance.rb:22:in `call'
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/stripe-ruby-mock-2.0.0/lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/stripe-1.19.0/lib/stripe/api_operations/request.rb:15:in `request'
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/stripe-1.19.0/lib/stripe/api_operations/create.rb:6:in `create'
     # ./app/worker/stripe_transaction_worker.rb:11:in `block in perform'
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
     # ./app/worker/stripe_transaction_worker.rb:7:in `perform'
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/testing.rb:74:in `block in raw_push'
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/testing.rb:69:in `each'
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/testing.rb:69:in `raw_push'
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/client.rb:68:in `push'
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/worker.rb:85:in `client_push'
     # /Users/jakub/.rvm/gems/ruby-2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/worker.rb:40:in `perform_async'
     # ./spec/workers/stripe_transaction_worker_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/workers/stripe_transaction_worker_spec.rb:41:in `block (5 levels) in <top (required)>'
```

In my gemfile:
```
Using stripe 1.19.0
Using stripe-ruby-mock 2.0.3
```

when I downgraded stripe to 1.15.0 it works nicely though.

The code itself looks like:
```ruby
       charge = Stripe::Charge.create({
          amount: transaction.amount,
          currency: 'gbp',
          card: transaction.options[:token],
          description: 'Coffee Shipment'
        }, {
          idempotency_key: uuid
        })
```

**Comment by EddM** [comment]
Thanks, fixed in #181
