### ISSUE TITLE
Stripe::Charge creation requires minimum charge amount

### ISSUE THREAD

**Issue by theoretick** [rebelidealist/stripe-ruby-mock#193]
`Stripe::Charge#create` [currently enforces a minimum charge amount](https://stripe.com/docs/api/ruby#create_charge) equivalent to $0.50 USD.  This error case is not handled in stripe-ruby-mock currently.

The logic in adding this check is a bit complex due to currency conversions. For example:

stripe-ruby:
```
»  Stripe::Charge.create(amount: 1, currency: 'usd', card: card)
Stripe::InvalidRequestError: Amount must be at least 50 cents
from /home/theoretick/.gem/ruby/2.1.2/gems/stripe-1.16.0/lib/stripe.rb:232:in `handle_api_error'

»  Stripe::Charge.create(amount: 32, currency: 'gbp', card: card)
Stripe::InvalidRequestError: Amount must convert to at least 50 cents. £0.32 converts to approximately $0.49.
from /home/theoretick/.gem/ruby/2.1.2/gems/stripe-1.16.0/lib/stripe.rb:232:in `handle_api_error'

»  Stripe::Charge.create(amount: 51, currency: 'jpy', card: card)
Stripe::InvalidRequestError: Amount must convert to at least 50 cents. ¥51 converts to approximately $0.42.
from /home/theoretick/.gem/ruby/2.1.2/gems/stripe-1.16.0/lib/stripe.rb:232:in `handle_api_error'
```

**Comment by abdulhanan00** [comment]
@theoretick  did you get any answer

**Comment by theoretick** [comment]
@abdulhanan00 nope, and I haven't used this library in probably 5 years 😁. But based on the notice [in the README](https://github.com/stripe-ruby-mock/stripe-ruby-mock#request-looking-for-more-core-contributors) the current project state is that it lacks a sufficient number of core contributors, so it's understandable there may be some deep backlog items.

If you're interested in trying to fix this I'm sure others would love to have the benefit! I'm pretty unfamiliar with it at this point so I cannot offer much guidance beyond introducing [a new error type](https://github.com/stripe-ruby-mock/stripe-ruby-mock#built-in-card-errors).

**Comment by abdulhanan00** [comment]
Hi Lucas Charles,

 Thanks for your reply.
