### ISSUE TITLE
PG::ConnectionBad: PQconsumeInput() being caused ActiveRecord::Migration.maintain_test_schema! and/or DatabaseCleaner

### ISSUE THREAD

**Issue by georgemillo** [rebelidealist/stripe-ruby-mock#217]
I'm following the tutorial at http://www.jeffthomas.xyz/integration-tests-with-stripe/ but it's not working.

In brief:

    gem 'stripe',            '1.20.1'
    
    group :test do
      gem 'thin'
      gem 'stripe-ruby-mock', '~> 2.1.1'
   end

   # rails_helper:

   require 'thin'
   require 'stripe_mock'
   StripeMock.spawn_server

   # spec file:

    before { StripeMock.start_client }
    after { StripeMock.start_client }

    it "creates a new user" do
      # (fill in form with credit card details)
      expect{click_button "Sign up"}.to change{User.count}.by(1)
    end

But when I run the test I get:

    Daemon has started successfully
    Killing server at ./stripe-mock-server.pid 
    Stopped PID: 18987 at ./stripe-mock-server.pid
    /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec': PG::ConnectionBad: PQconsumeInput() :               SELECT COUNT(*) (ActiveRecord::StatementInvalid)
              FROM pg_class c
              LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
              WHERE c.relkind IN ('r','v','m') -- (r)elation/table, (v)iew, (m)aterialized view
              AND c.relname = 'schema_migrations'
              AND n.nspname = ANY (current_schemas(false))
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:105:in `table_exists?'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:843:in `get_all_versions'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:855:in `needs_migration?'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:397:in `load_schema_if_pending!'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:412:in `block in maintain_test_schema!'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:640:in `suppress_messages'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:417:in `method_missing'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:412:in `maintain_test_schema!'
	from /path/to/my/app/spec/rails_helper.rb:20:in `<top (required)>'

Note that last line of the stack trace: `rails_helper.rb:20` is `ActiveRecord::Migration.maintain_test_schema!` 

Why is `maintain_test_schema` conflicting with the Stripe mock server?

Truth be told, I didn't notice that `maintain_test_schema` was the problem until I started writing this issue... so I tried the obvious solution and moved the line 'Stripe.spawn_server` **below** the call to `maintain_test_schema`. Now the test fails (in the RSpec sense) instead of crashing completely, and the failure message is something similar:

     Failure/Error: Unable to find matching line from backtrace
     ActiveRecord::StatementInvalid:
       PG::ConnectionBad: PQconsumeInput() : BEGIN

That's being triggered by `DatabaseCleaner.start`, which is running in a `before(:each)` block that's also in my spec_helper.

Are these two errors related? What am I doing wrong? Why isn't the mock server working properly?

**Comment by kashifnaseer** [comment]
I'm also getting this error, any idea, how i can fix it ?

**Comment by cmoel** [comment]
I'm having the same issue. @georgemillo did you get any further with this?

**Comment by jagthedrummer** [comment]
I ran into this too, and eventually figured out that I could get it to work by adding this after `StripeMock.spawn_server`:

`ActiveRecord::Base.connection.reconnect!`

So, my cucumber before set up looks like

```
Before do
  StripeMock.start_server
  ActiveRecord::Base.connection.reconnect!
end
```
