### ISSUE TITLE
StripeMock.spawn_server throws an error when passing "-e" option to RSpec.

### ISSUE THREAD

**Issue by georgemillo** [rebelidealist/stripe-ruby-mock#219]
RSpec has a command line option "-e" or "--example" that lets you filter tests by their description.

    $ rspec -r "creates a new user"
    # => This will run the test defined by 'it "creates a new user"'.

But with stripe-ruby-mock installed, trying to run rspec with the `-e` flag throws an error:

    $ rspec --example "creates a new user" spec/features/users/sign_up_spec.rb
    /Users/george/.rvm/gems/ruby-2.2.1/gems/dante-0.2.0/lib/dante/runner.rb:212:in `parse_options': invalid option: --example (OptionParser::InvalidOption)
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/dante-0.2.0/lib/dante/runner.rb:50:in `execute'
	from /Users/george/.rvm/gems/ruby-2.2.1/gems/stripe-ruby-mock-2.1.1/lib/stripe_mock/api/server.rb:19:in `spawn_server'
	from /Users/george/path/to/my/app/spec/spec_helper.rb:11:in `<top (required)>'

The offending line, spec_helper:11, is "StripeMock.spawn_server". Commenting that line out makes the `-e` flag work as intended, but then of course my tests don't work because the StripeMock server isn't running.

Looks like the problem is being caused by the Dante gem but I've never used that and don't know what it does.

**Comment by kathyonu** [comment]
May I recommend you reinstall Dante .. I had a different problem, and doing this fixed it .. 
I trashed my Gemfile.lock, simply move it to the trash.  Doing so gives your bundle a change to cleanly reset all the dependencies. Then ..

$ gem uninstall dante
$ bundle
$ gem install dante
$ bundle update

It installed the exact same version, and yet doing this worked.
I can't explain it, I just know it worked for me.
Hope it works for you.

**Comment by georgemillo** [comment]
Tried your exact steps but it didn't fix the problem.

For the record, here's my `Gemfile.lock`:

```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.1)
      actionview (= 4.2.1)
      activesupport (= 4.2.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    activejob (4.2.1)
      activesupport (= 4.2.1)
      globalid (>= 0.3.0)
    activemodel (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
    activerecord (4.2.1)
      activemodel (= 4.2.1)
      activesupport (= 4.2.1)
      arel (~> 6.0)
    activesupport (4.2.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    arel (6.0.0)
    aws-sdk (1.61.0)
      aws-sdk-v1 (= 1.61.0)
    aws-sdk-v1 (1.61.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    blankslate (3.1.3)
    bootstrap-sass (3.2.0.2)
      sass (~> 3.2)
    builder (3.2.2)
    byebug (3.5.1)
      columnize (~> 0.8)
      debugger-linecache (~> 1.2)
      slop (~> 3.6)
    capybara (2.4.4)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cliver (0.3.2)
    cocaine (0.5.7)
      climate_control (>= 0.0.3, < 1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    columnize (0.9.0)
    countries (0.9.3)
      currencies (~> 0.4.2)
    country_select (2.1.1)
      countries (>= 0.9.3, < 0.10.0)
    crack (0.4.2)
      safe_yaml (~> 1.0.0)
    currencies (0.4.2)
    dante (0.2.0)
    database_cleaner (1.3.0)
    debug_inspector (0.0.2)
    debugger-linecache (1.2.0)
    devise (3.4.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    diff-lcs (1.2.5)
    domain_name (0.5.24)
      unf (>= 0.0.5, < 1.0.0)
    erubis (2.7.0)
    execjs (2.5.2)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faker (1.2.0)
      i18n (~> 0.5)
    figaro (1.0.0)
      thor (~> 0.14)
    font-awesome-sass (4.3.2.1)
      sass (~> 3.2)
    globalid (0.3.5)
      activesupport (>= 4.1.0)
    hike (1.2.3)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    i18n (0.7.0)
    jimson-temp (0.9.5)
      blankslate (>= 3.1.2)
      multi_json (~> 1.0)
      rack (~> 1.4)
      rest-client (~> 1.0)
    jquery-rails (4.0.3)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-turbolinks (2.1.0)
      railties (>= 3.1.0)
      turbolinks
    json (1.8.2)
    loofah (2.0.1)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.5)
    mini_portile (0.6.2)
    minitest (5.6.1)
    multi_json (1.11.0)
    netrc (0.10.3)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    order_order (1.1.0)
      activerecord
    orderly (0.0.2)
    orm_adapter (0.5.0)
    paperclip (4.2.1)
      activemodel (>= 3.0.0)
      activesupport (>= 3.0.0)
      cocaine (~> 0.5.3)
      mime-types
    pg (0.18.1)
    poltergeist (1.6.0)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    puma (2.11.2)
      rack (>= 1.1, < 2.0)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.6.0)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.1)
      actionmailer (= 4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      activemodel (= 4.2.1)
      activerecord (= 4.2.1)
      activesupport (= 4.2.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.6)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.4)
    rails_stdout_logging (0.0.3)
    railties (4.2.1)
      actionpack (= 4.2.1)
      activesupport (= 4.2.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    rest-client (1.8.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rspec-core (3.1.7)
      rspec-support (~> 3.1.0)
    rspec-expectations (3.1.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.1.0)
    rspec-mocks (3.1.3)
      rspec-support (~> 3.1.0)
    rspec-rails (3.1.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.1.0)
      rspec-expectations (~> 3.1.0)
      rspec-mocks (~> 3.1.0)
      rspec-support (~> 3.1.0)
    rspec-support (3.1.2)
    safe_yaml (1.0.4)
    sass (3.2.19)
    sass-rails (4.0.5)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.2)
      sprockets (~> 2.8, < 3.0)
      sprockets-rails (~> 2.0)
    shoulda-matchers (2.8.0)
      activesupport (>= 3.0.0)
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    slop (3.6.0)
    spring (1.1.3)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.2.4)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    stripe (1.20.1)
      json (~> 1.8.1)
      mime-types (>= 1.25, < 3.0)
      rest-client (~> 1.4)
    stripe-ruby-mock (2.1.1)
      dante (>= 0.2.0)
      jimson-temp
      stripe (= 1.20.1)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    vcr (2.9.3)
    warden (1.2.3)
      rack (>= 1.0)
    web-console (2.1.2)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    webmock (1.21.0)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
    websocket-driver (0.5.4)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  aws-sdk (~> 1.61.0)
  bootstrap-sass (~> 3.2.0)
  byebug (~> 3.5.1)
  capybara (~> 2.4.4)
  country_select (~> 2.1.0)
  database_cleaner (~> 1.3.0)
  devise (~> 3.4.1)
  factory_girl_rails (~> 4.5.0)
  faker (~> 1.2.0)
  figaro (~> 1.0.0)
  font-awesome-sass (~> 4.3.0)
  jquery-rails (~> 4.0.3)
  jquery-turbolinks (~> 2.1.0)
  order_order (~> 1.1.0)
  orderly
  paperclip (~> 4.2.1)
  pg (~> 0.18.1)
  poltergeist
  puma (~> 2.11.1)
  quiet_assets (~> 1.1.0)
  rails (= 4.2.1)
  rails_12factor (~> 0.0.3)
  rspec-rails (~> 3.1.0)
  sass-rails (~> 4.0.0)
  shoulda-matchers (~> 2.8.0)
  sinatra
  spring (~> 1.1.3)
  spring-commands-rspec (~> 1.0.2)
  stripe (= 1.20.1)
  stripe-ruby-mock (~> 2.1.1)
  turbolinks (~> 2.5.3)
  uglifier (~> 2.7.0)
  vcr
  web-console (~> 2.0)
  webmock
```

**Comment by excid3** [comment]
The problem is that Stripe Ruby Mock is grabbing ARGV and passing the rspec options to Dante. Since those same options aren't valid in the mock server, it chokes.

A hack is that you can set the ARGV to an empty array before calling spawn_server:

```ruby
  ARGV = [] # Reset ARGV so Dante will quit using rspec params
  StripeMock.spawn_server
```

**Comment by kathyonu** [comment]
@georgemillo , @excid3 To run live tests, I had to comment out StripeMock.spawn_server, and because i have StripeMock.start and .stop in before and after block for each set of tests, the `rspec live -t` works. I simply left it commented out.  
I tried the hack from @excid3 , and it works like a charm, tests now work, live or not.

**Comment by s2t2** [comment]
Confirming this issue (seeing `OptionParser::InvalidOption` error when try to pass `-e` when running rspec locally. 

This issue is also messing up our CI server's ability to run rspec, because it passes options as well and runs into the same `OptionParser::InvalidOption` error.

**Comment by tannerhallman** [comment]
I was able to resolve this by using:

```
  before { StripeMock.start }
  after { StripeMock.stop }
```

instead of `StripeMock.spawn_server`
