### ISSUE TITLE
"You must supply a valid card" error on factory_girl

### ISSUE THREAD

**Issue by ygamretuta** [rebelidealist/stripe-ruby-mock#232]
I create a stripe subscription before I create my user factory. I don't know if that works for the current  stripe-ruby-mock version but it did in the previous (my tests were running without the aforementioned error).

Here is the code:

```
factory :team_admin, class:'User' do
    name "Team Admin"
    email
    password "teamadmin"
    team_name "My Team"

    after(:build) do |ta|
      helper = StripeMock.create_test_helper
      plan = helper.create_plan(amount:500, interval:'month', name:'Basic', id:'basic', currency:'usd')
      token = helper.generate_card_token(last4: "9191", exp_year: 2016)
      customer = Stripe::Customer.create(email:ta.email, plan:'basic', description:ta.id, card:token)
      ta.customer_id = customer.id
    end

    after(:create) {|instance| create_list(:team_member, 2, user:instance)}
  end
```

```
factory :team_admin_trial, class:'User' do
    name 'Trial Team Admin'
    email
    password 'tialteamadmin'
    team_name 'My Team'
    
    factory :trialed_with_card do
      after(:build) do |instance|
        helper = StripeMock.create_test_helper
        Stripe::Plan.create(amount:500, interval:'month', name:'Basic Trial', id:'basic_trial', currency:'usd')
        token = StripeMock.generate_card_token(last4: "9191", exp_year: 2016)
        customer = Stripe::Customer.create(email:instance.email, description:instance.id, card: token, plan:'basic_trial')
        instance.customer_id = customer.id
      end
    end
```

```
TeamMembersController if team_admin logged in DELETE destroy does not allow team admin to delete a member not under him/her
     Failure/Error: Unable to find matching line from backtrace
     Stripe::InvalidRequestError:
       You must supply a valid card
     # ./spec/factories/users.rb:63:in `block (3 levels) in <top (required)>'
     # ./spec/support/controller_macros.rb:5:in `block in login_team_admin'
```

I also ran it using the helper

for reference here is the spec/support/controller_macros file:

```
module ControllerMacros
  def login_team_admin
    before(:each) do
      @request.env['devise.mapping'] = Devise.mappings[:user]
      @team_admin = FactoryGirl.create(:team_admin)
      sign_in @team_admin
    end
  end

  def login_user
    before(:each) do
      @request.env['devise.mapping'] = Devise.mappings[:user]
      @user = FactoryGirl.create(:user)
      sign_in @user
    end
  end
end
```

**Comment by alexmamonchik** [comment]
use `source` instead of `card` for Stripe::Customer.create. Changes in [Stripe] (https://stripe.com/docs/api#create_customer)

**Comment by ygamretuta** [comment]
thanks. solved ^_^
