### ISSUE TITLE
stripe 1.29.0 and newest breaks transfer tests

### ISSUE THREAD

**Issue by alexmamonchik** [rebelidealist/stripe-ruby-mock#270]
``` shell
$ rspec
```
local tests failed

```shell
1) StripeMock::Instance behaves like Transfer API listing transfers without params retrieves all tripe transfers
     Failure/Error: expect(Stripe::Transfer.all.count).to eq(3)
     TypeError:
       no implicit conversion of Symbol into Integer
     Shared Example Group: "Transfer API" called from ./spec/support/stripe_examples.rb:21
     # ./spec/shared_stripe_examples/transfer_examples.rb:26:in `block (3 levels) in <top (required)>'

  2) StripeMock::Instance behaves like Transfer API listing transfers accepts a limit param
     Failure/Error: expect(Stripe::Transfer.all(limit: 2).count).to eq(2)
     TypeError:
       no implicit conversion of Symbol into Integer
     Shared Example Group: "Transfer API" called from ./spec/support/stripe_examples.rb:21
     # ./spec/shared_stripe_examples/transfer_examples.rb:30:in `block (3 levels) in <top (required)>'

  3) StripeMock::Instance behaves like Transfer API listing transfers filters the search to a specific recipient
     Failure/Error: expect(Stripe::Transfer.all(recipient: r2.id).count).to eq(1)
     TypeError:
       no implicit conversion of Symbol into Integer
     Shared Example Group: "Transfer API" called from ./spec/support/stripe_examples.rb:21
     # ./spec/shared_stripe_examples/transfer_examples.rb:37:in `block (3 levels) in <top (required)>'

  4) StripeMock Server behaves like Transfer API listing transfers without params retrieves all tripe transfers
     Failure/Error: expect(Stripe::Transfer.all.count).to eq(3)
     TypeError:
       no implicit conversion of Symbol into Integer
     Shared Example Group: "Transfer API" called from ./spec/support/stripe_examples.rb:21
     # ./spec/shared_stripe_examples/transfer_examples.rb:26:in `block (3 levels) in <top (required)>'

  5) StripeMock Server behaves like Transfer API listing transfers accepts a limit param
     Failure/Error: expect(Stripe::Transfer.all(limit: 2).count).to eq(2)
     TypeError:
       no implicit conversion of Symbol into Integer
     Shared Example Group: "Transfer API" called from ./spec/support/stripe_examples.rb:21
     # ./spec/shared_stripe_examples/transfer_examples.rb:30:in `block (3 levels) in <top (required)>'

  6) StripeMock Server behaves like Transfer API listing transfers filters the search to a specific recipient
     Failure/Error: expect(Stripe::Transfer.all(recipient: r2.id).count).to eq(1)
     TypeError:
       no implicit conversion of Symbol into Integer
     Shared Example Group: "Transfer API" called from ./spec/support/stripe_examples.rb:21
     # ./spec/shared_stripe_examples/transfer_examples.rb:37:in `block (3 levels) in <top (required)>'

```

**Comment by alexmamonchik** [comment]
I play with byebug
``` shell
[22, 31] in /usr/local/Cellar/rbenv/0.4.0/versions/2.1.6/lib/ruby/gems/2.1.0/gems/stripe-1.30.2/lib/stripe/stripe_object.rb
   22:
   23:     def self.construct_from(values, opts={})
   24:       values = Stripe::Util.symbolize_names(values)
   25:
   26:       # work around protected #initialize_from for now
=> 27:       self.new(values[:id]).send(:initialize_from, values, opts)
   28:     end
   29:
   30:     # Determines the equality of two Stripe objects. Stripe objects are
   31:     # considered to be equal if they have the same set of values and each one
(byebug) values
{:id=>"test_tr_2", :object=>"transfer", :amount=>100, :amount_reversed=>0, :application_fee=>nil, :balance_transaction=>"txn_16u4Hp2eZvKYlo2CjVTeHRJk", :bank_account=>{:id=>"ba_16vvOF2eZvKYlo2CqfY8d9Ve", :object=>"bank_account", :bank_name=>"STRIPE TEST BANK", :country=>"US", :currency=>"usd", :fingerprint=>"1JWtPxqbdX5Gamtc", :last4=>"6789", :routing_number=>"110000000", :status=>"new"}, :created=>1444852710, :currency=>"usd", :date=>1444852710, :description=>nil, :destination=>"ba_16vvOF2eZvKYlo2CqfY8d9Ve", :failure_code=>nil, :failure_message=>nil, :livemode=>false, :metadata=>{}, :recipient=>"test_rp_1", :reversals=>{:object=>"list", :data=>[], :has_more=>false, :total_count=>0, :url=>"/v1/transfers/tr_16vvOM2eZvKYlo2CSnamxtXb/reversals"}, :reversed=>false, :source_transaction=>nil, :statement_descriptor=>nil, :status=>"paid", :type=>"bank_account"}
{:id=>"test_tr_3", :object=>"transfer", :amount=>100, :amount_reversed=>0, :application_fee=>nil, :balance_transaction=>"txn_16u4Hp2eZvKYlo2CjVTeHRJk", :bank_account=>{:id=>"ba_16vvOF2eZvKYlo2CqfY8d9Ve", :object=>"bank_account", :bank_name=>"STRIPE TEST BANK", :country=>"US", :currency=>"usd", :fingerprint=>"1JWtPxqbdX5Gamtc", :last4=>"6789", :routing_number=>"110000000", :status=>"new"}, :created=>1444852710, :currency=>"usd", :date=>1444852710, :description=>nil, :destination=>"ba_16vvOF2eZvKYlo2CqfY8d9Ve", :failure_code=>nil, :failure_message=>nil, :livemode=>false, :metadata=>{}, :recipient=>"test_rp_1", :reversals=>{:object=>"list", :data=>[], :has_more=>false, :total_count=>0, :url=>"/v1/transfers/tr_16vvOM2eZvKYlo2CSnamxtXb/reversals"}, :reversed=>false, :source_transaction=>nil, :statement_descriptor=>nil, :status=>"paid", :type=>"bank_account"}
{:id=>"test_tr_4", :object=>"transfer", :amount=>100, :amount_reversed=>0, :application_fee=>nil, :balance_transaction=>"txn_16u4Hp2eZvKYlo2CjVTeHRJk", :bank_account=>{:id=>"ba_16vvOF2eZvKYlo2CqfY8d9Ve", :object=>"bank_account", :bank_name=>"STRIPE TEST BANK", :country=>"US", :currency=>"usd", :fingerprint=>"1JWtPxqbdX5Gamtc", :last4=>"6789", :routing_number=>"110000000", :status=>"new"}, :created=>1444852710, :currency=>"usd", :date=>1444852710, :description=>nil, :destination=>"ba_16vvOF2eZvKYlo2CqfY8d9Ve", :failure_code=>nil, :failure_message=>nil, :livemode=>false, :metadata=>{}, :recipient=>"test_rp_1", :reversals=>{:object=>"list", :data=>[], :has_more=>false, :total_count=>0, :url=>"/v1/transfers/tr_16vvOM2eZvKYlo2CSnamxtXb/reversals"}, :reversed=>false, :source_transaction=>nil, :statement_descriptor=>nil, :status=>"paid", :type=>"bank_account"}
(byebug) values[:id]
*** TypeError Exception: no implicit conversion of Symbol into Integer


(byebug) values.class
Array
(byebug)
```

**Comment by louim** [comment]
I think #265 is related.

**Comment by alexmamonchik** [comment]
@louim I think no, but #263 yes. In latest updates of the stripe gem I see a lot of bugs related to Stripe::StripeObject
