### ISSUE TITLE
Getting a 

### ISSUE THREAD

**Issue by YPCrumble** [rebelidealist/stripe-ruby-mock#373]
When I run $`stripe-mock-server` in my console I get this response:

    Starting StripeMock server on port 4999

However, if I try to make a request to the server I get the following error:

> FNo:DRb::DRbConnError:	mesgI" too large packet 1195725856:ET:bt[I"I/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/drb/drb.rb:582:in `load';FI"Q/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/drb/drb.rb:621:in `recv_request';FI"Q/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/drb/drb.rb:931:in `recv_request';FI"V/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/drb/drb.rb:1599:in `init_with_client';FI"S/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/drb/drb.rb:1611:in `setup_message';FI"M/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/drb/drb.rb:1563:in `perform';FI"c/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/drb/drb.rb:1657:in `block (2 levels) in main_loop';FI"J/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/drb/drb.rb:1653:in `loop';FI"X/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/drb/drb.rb:1653:in `block in main_loop';F:bt_locations@

**Comment by adrienverge** [comment]
Hi, I encounter the same error.

I've tested on two up-to-date Linux machines (one Fedora and one Ubuntu).

Steps followed to reproduce the problem:
```shell
$ git clone git@github.com:rebelidealist/stripe-ruby-mock.git
$ cd stripe-ruby-mock
$ bundle install
$ ./bin/stripe-mock-server &
Starting StripeMock server on port 4999
$ curl localhost:4999/v1/customers
curl: (56) Recv failure: Connection reset by peer
FRo:DRb::DRbConnErro:	mesgI" too large packet 1195725856:ET:bt[I"-/usr/share/ruby/drb/drb.rb:582:in `load';FI"5/usr/share/ruby/drb/drb.rb:621:in `recv_request';FI"5/usr/share/ruby/drb/drb.rb:931:in `recv_request';FI":/usr/share/ruby/drb/drb.rb:1599:in `init_with_client';FI"7/usr/share/ruby/drb/drb.rb:1611:in `setup_message';FI"1/usr/share/ruby/drb/drb.rb:1563:in `perform';FI"G/usr/share/ruby/drb/drb.rb:1657:in `block (2 levels) in main_loop';FI"./usr/share/ruby/drb/drb.rb:1653:in `loop';FI"</usr/share/ruby/drb/drb.rb:1653:in `block in main_loop';F:bt_locations@
```

Following some advice found on the Internet, I've tried adding the following in `lib/stripe_mock/server.rb`:
```ruby
DRb::DRbServer.default_load_limit 1195725856
```
but, then, the request freezes and times out.

```shell
$ ruby --version
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
```

**Comment by adrienverge** [comment]
Tested on two more systems (another Fedora and a CentOS virtual machine): the same problem happens.
