### ISSUE TITLE
Cannot create Refund by Stripe::Refund.create

### ISSUE THREAD

**Issue by AndKiel** [rebelidealist/stripe-ruby-mock#391]
Cannot create Refund by `Stripe::Refund.create(charge: stripe_id, amount: cost)`.

Stacktrace below:

```
NoMethodError:
  undefined method '[]' for nil:NilClass
# /usr/local/bundle/gems/stripe-ruby-mock-2.3.1/lib/stripe_mock/api/client.rb:33:in 'redirect_to_mock_server'
# /usr/local/bundle/gems/stripe-ruby-mock-2.3.1/lib/stripe_mock/api/instance.rb:22:in 'call'
# /usr/local/bundle/gems/stripe-ruby-mock-2.3.1/lib/stripe_mock/api/instance.rb:22:in 'block in alias_stripe_method'
# /usr/local/bundle/gems/stripe-1.56.1/lib/stripe/api_operations/request.rb:15:in 'request'
# /usr/local/bundle/gems/stripe-1.56.1/lib/stripe/api_operations/create.rb:5:in 'create'
```

But `Stripe::Charge.retrieve(stripe_id).refund(amount: cost)` works just fine.

**Comment by peco8** [comment]
+1

**Comment by peco8** [comment]
As I tried mocking
```
refund_mock = Stripe::Refund.create(
             charge: invoice.stripe_charge_id
           )
```
It does not work.

**Comment by alexmamonchik** [comment]
@AndKiel what version of gem do you use?

**Comment by Sylvain** [comment]
This PR https://github.com/rebelidealist/stripe-ruby-mock/pull/400 will make it work. The Refund endpoint was missing.

**Comment by alexmamonchik** [comment]
thanks!
