### ISSUE TITLE
NameError: undefined method `request' for class `#<Class:Stripe>'

### ISSUE THREAD

**Issue by siaw23** [rebelidealist/stripe-ruby-mock#441]
I'm using `ruby 2.4.1`
 and 

```
stripe (2.12.0)
stripe-ruby-mock (2.2.3)
```
Just thought maybe `stripe-ruby-mock` could use some update? Or I could be missing something. Below is my stack trace if someone could point me in some good direction.

```
NameError: undefined method `request' for class `#<Class:Stripe>'
Did you mean?  require
/usr/local/bundle/gems/stripe-ruby-mock-2.2.3/lib/stripe_mock/api/instance.rb:5:in `method'
/usr/local/bundle/gems/stripe-ruby-mock-2.2.3/lib/stripe_mock/api/instance.rb:5:in `<module:StripeMock>'
/usr/local/bundle/gems/stripe-ruby-mock-2.2.3/lib/stripe_mock/api/instance.rb:1:in `<top (required)>'
/usr/local/bundle/gems/skylight-1.3.1/lib/skylight/probes.rb:81:in `require'
/usr/local/bundle/gems/skylight-1.3.1/lib/skylight/probes.rb:81:in `require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/stripe-ruby-mock-2.2.3/lib/stripe_mock.rb:24:in `<top (required)>'
/usr/local/bundle/gems/skylight-1.3.1/lib/skylight/probes.rb:81:in `require'
/usr/local/bundle/gems/skylight-1.3.1/lib/skylight/probes.rb:81:in `require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/srv/app/test/test_helper.rb:12:in `<top (required)>'
/usr/local/bundle/gems/skylight-1.3.1/lib/skylight/probes.rb:81:in `require'
/usr/local/bundle/gems/skylight-1.3.1/lib/skylight/probes.rb:81:in `require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/srv/app/test/jobs/api_client_callback_job_test.rb:1:in `<top (required)>'
/usr/local/bundle/gems/skylight-1.3.1/lib/skylight/probes.rb:81:in `require'
/usr/local/bundle/gems/skylight-1.3.1/lib/skylight/probes.rb:81:in `require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/test_unit/sub_test_task.rb:114:in `each'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/test_unit/sub_test_task.rb:113:in `each'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/test_unit/sub_test_task.rb:20:in `invoke_rake_task'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/bundle/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/bundle/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/bundle/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/usr/local/bundle/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/usr/local/bundle/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/bundle/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/usr/local/bundle/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/usr/local/bundle/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => test:run => test:jobs

```

**Comment by colinpetruno** [comment]
Right now it looks like this gem is incompatible with the newest stripe gem versions (2.0+).  It looks like they are working on it as stated in https://github.com/rebelidealist/stripe-ruby-mock/pull/437 so this can probably be closed. 

For reference, the method was removed in the stripe gem here:
https://github.com/stripe/stripe-ruby/commit/1886d9a625494f089b888396efae8bc8bab2b1da#diff-7bd095922baff1048f819a71f5df2e2c
