### ISSUE TITLE
Billing attribute missing from subscription object

### ISSUE THREAD

**Issue by StephRicardo** [rebelidealist/stripe-ruby-mock#502]
**From Stripe:**
`billing` -  Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay this subscription at the end of the cycle using the default source attached to the customer. When sending an invoice, Stripe will email your customer an invoice with payment instructions.

**Subscription Item with `stripe-ruby-mock`:**
```json
#<Stripe::Subscription:0x49e2894 id=test_su_4> JSON: {
  "id": "test_su_4",
  "created": 1478204116,
  "current_period_start": 1515688836,
  "current_period_end": 1518367236,
  "status": "active",
  "plan": {"id":"test","object":"plan","amount":0,"created":1466698898,"currency":"usd","interval":"month","interval_count":1,"livemode":false,"metadata":{},"name":"StripeMock Default Plan ID","statement_descriptor":null,"trial_period_days":null},
  "items": {"object":"list","data":[{"id":"si_1AwFf62eZvKYlo2C9u6Dhf9","created":1504035973,"metadata":{},"object":"subscription_item","plan":{"amount":999,"created":1504035972,"currency":"usd"},"quantity":1}]},
  "cancel_at_period_end": false,
  "canceled_at": null,
  "ended_at": null,
  "start": 1308595038,
  "object": "subscription",
  "trial_start": null,
  "trial_end": null,
  "customer": "test_cus_3",
  "quantity": 1,
  "tax_percent": null,
  "discount": null,
  "metadata": {}
}
```

**Situation:**
I have a method in my project that saves the billing attribute and other subscription data to my database.  This works live, but this is the error I receive during testing: 

```shell
NoMethodError:
       undefined method `billing' for #<Stripe::Subscription:0x0000000825e510>
     # /usr/local/bundle/gems/stripe-3.8.1/lib/stripe/stripe_object.rb:296:in `method_missing'
     # ./app/forms/user_registration_form.rb:89:in `save_membership_subscription'
     # ./app/forms/user_registration_form.rb:46:in `block in process'
     # ./app/forms/user_registration_form.rb:43:in `process'
     # ./spec/forms/user_registration_form_spec.rb:117:in `block (3 levels) in <top (required)>'
```

**Comment by StephRicardo** [comment]
I've created a PR for this small issue: [PR #507](https://github.com/rebelidealist/stripe-ruby-mock/pull/507)

**Comment by StephRicardo** [comment]
PR Merged! https://github.com/rebelidealist/stripe-ruby-mock/pull/507
